# --- Conectividad ---
# Escucha en el puerto 1883 y acepta conexiones de cualquier IP (como el ESP32)
listener 1883 0.0.0.0
allow_anonymous true

# --- Persistencia ---
# Guarda los mensajes del bróker en el disco para que no se borren al apagar el contenedor
persistence true
persistence_location /mosquitto/data/

# --- Registros / Logs ---
# Guarda un registro de quién se conecta y qué errores ocurren
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout