version: '3.8'

services:
  # --- BRÓKER MQTT (El cartero del proyecto) ---
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883" # Puerto estándar para la comunicación del ESP32 y n8n
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # --- AUTOMATIZACIÓN (n8n) ---
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/

      # Configuración del Runner de Python externo
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_BROKER_PORT=5679
      - N8N_RUNNERS_AUTH_TOKEN=token
      - N8N_NATIVE_PYTHON_RUNNER=true

      # Zona horaria (Islas Canarias)
      - GENERIC_TIMEZONE=Atlantic/Canary
      - TZ=Atlantic/Canary
      - N8N_USER_FOLDER=/home/node/.n8n
    volumes:
      - n8n_data:/home/node/.n8n
      - ./archivos_n8n:/home/node/.n8n-files
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mosquitto # Espera a que el bróker MQTT esté listo

  # Contenedor separado que ejecuta el runner de Python
  n8n-python-runner:
    image: n8nio/runners:latest
    container_name: n8n-python-runner
    restart: unless-stopped
    environment:
      - N8N_RUNNERS_AUTH_TOKEN=token
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n:5679
      - RUNNER_TYPE=python
    depends_on:
      - n8n

  # --- BASE DE DATOS Y VISUALIZACIÓN ---
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  n8n_data:
    driver: local
  influxdb_data:
  grafana_data: